foreground #fdfdfd
background #1b1c1d

selection_foreground #1b1c1d
selection_background #fdfdfd

cursor            #e2201f
cursor_text_color #1b1c1d

color0                #4d4d4d
color8                #5a5a5a
color1                #c70031
color9                #f01578
color2                #29cf13
color10               #6ce05c
color3                #d8e30e
color11               #f3f79e
color4                #3449d1
color12               #97a4f7
color5                #8400ff
color13               #c495f0
color6                #0798ab
color14               #68f2e0
color7                #e2d1e3
color15               #ffffff

active_tab_foreground    #1b1c1d
active_tab_background    #e2201f

inactive_tab_foreground  #f5f0f0
inactive_tab_background  #1b1c1d
tab_bar_background       #1b1c1d
