-- AUTO-GENERATED by apply_theme.py - edit palette.json, not this file.
-- Loaded from hyprland.lua with: local colors = require("colors")

return {
    background      = "rgba(1b1c1dff)",
    foreground      = "rgba(fdfdfdff)",
    accent          = "rgba(4166f5ff)",
    border_inactive = "rgba(585959aa)",
    shadow          = "rgba(1a1b1cee)",
}
